### PR TITLE
build rootfs for arm64

### PR DESCRIPTION
**Pull request by wineee**

### CODE REVIEW

**Comment by wineee** [comment]
stage2 有点问题，我再调整一下

**Comment by chenchongbiao** [comment]
> stage2 有点问题，我再调整一下

行

**Review by chenchongbiao — APPROVED** [review]

**Review by chenchongbiao — APPROVED** [review]

**Comment by wineee** [comment]
https://github.com/deepin-community/deepin-rootfs/pull/2

**Pull request merged**
